### ISSUE TITLE
いたずらや対立潰し、都民であることの確認はどうするのか（荒らし対策について）

### ISSUE THREAD

**Issue by jene8774** [takahiroanno2024/election2024#144]
### 政策ビジョン

民主主義

### 政策

現状ネットでの進言は、都民でなかろうが自由に書き込めます。現に私は東京都民ではありません。
やろうと思えば外国人でもDEEPLのようなAIの翻訳で日本人と判別できない書き込みができます。（いい意味で使えば在日外国人との意思疎通は便利になるとは思います）

すると、善性のある純粋な東京都民だけでなく、東京とは関係のないいたずら心をもつ人や、自分の意見を通したいだけの対立潰しをしたがる人、また政治的な悪意ある海外の他者が扇動目的でブロードリスニングを混乱させることがあると思います。
いわゆるネット荒らしです。

ipアドレスで都民であることを確かめるとしても、スマホのipや、一時的に東京外にいる東京都民を判別できないのではないでしょうか。
またAIで荒らしかどうかを判別して悪そうな書き込みを弾くとしても、それは行政による検閲の一種になってしまうのではないでしょうか。

今の所Twitterもインプレゾンビを撲滅できていません。匿名掲示板も荒らしを排除できていません。この対策は考える必要があると思います

### 必要だと思ったきっかけ

オンラインでのコミュニケーションの歴史には常にネット荒らしが切っても切れない関係にあるので。

### なぜ必要か

荒らしをどうにかできない限り正常な意見が反映されないから

### この Issue で議論したいこと

荒らし排除の効果的な方法はあるのかについて。

### 調べたこと（裏付けとなる事実・ファクト）

私自身がまず東京都民ではないという主観的事実。
AI翻訳であるDEEPLを長く実用しての日本人と遜色ない翻訳の精度の実感

### 自由記述欄

いまはまだ、GitHubに積極的にアクセスできる水準の人や安野たかひろさんへの技術的な好奇心のある人しかここにいないだろうからまともに見えるけど、都民の中には意外とアホで自分勝手で文句ばっかり言いながらも自分では何もしたがらないろくでもない人もけっこういると思うので、そして行政というのはそういうダメダメな人こそ掬い上げる必要のある役割があるので、多角的な視点と不寛容な他者への忍耐が科学技術でどう解決できるかが見物です。

**Comment by RyutaroHashimoto** [comment]
今後もこのような政策議論の場は続いてほしいなと思っており、最大の懸念である外国人による選挙介入について調べていました。

結果として、現状の法制度として外国人が選挙運動に参加することは禁止されていないとのことでした。
[弁護士ドットコムの参考記事](https://www.bengo4.com/c_18/n_6831/)

現状の状態が良いかどうかは別として、外国人の投稿などは法律では禁止されていないため(当然ながら都民以外の参加についても禁止されていない)、我々一般人が都民かどうかの判定などを議論するのは時期早尚だと思います。

運営側でまず、都民以外の参加を認めるかどうか決める必要があると思います。

**Comment by jene8774** [comment]
> 今後もこのような政策議論の場は続いてほしいなと思っており、最大の懸念である外国人による選挙介入について調べていました。
> 
> 結果として、現状の法制度として外国人が選挙運動に参加することは禁止されていないとのことでした。 [弁護士ドットコムの参考記事](https://www.bengo4.com/c_18/n_6831/)
> 
> 現状の状態が良いかどうかは別として、外国人の投稿などは法律では禁止されていないため(当然ながら都民以外の参加についても禁止されていない)、我々一般人が都民かどうかの判定などを議論するのは時期早尚だと思います。
> 
> 運営側でまず、都民以外の参加を認めるかどうか決める必要があると思います。

たしかに、今このgithubの場で都民である必要があるかというのを考えるのは早いかもしれないですね。

同時に、将来的に安野さんのマニフェストにあるLINEでのブロードリスニングなどが正式に開始されたときに、いずれどこかのタイミングで誰までがブロードリスニングに参加できるかは定めてもらう必要はありそうじゃないかと思ってます。

**Comment by take365** [comment]
（私も都民じゃないので）参加できないようにすることには反対ですが、
例えばマイナンバーカードを使用した認証により都民であることの証明をした人は
そのフィルターで判断してもらうとかの工夫はよいと思います。
全体では賛成xx％、都民に限定すると賛成xx%とか。

**Comment by air-hand** [comment]
議論に参加できないようにするのは反対ですが、あくまで東京都知事なので都民かどうかなどでトリアージができるような手段を得ることは今後必須だと思います。
現状の選挙戦を見ていても、 @jene8774 さんのおっしゃるように都民の意見なのかどうかがわからないものが散見されるので。

**Comment by tokshibata** [comment]
チーム安野の政策立案メンバーです！
本Issueの議論を受け、以下のプルリクエストを立てました！
https://github.com/takahiroanno2024/election2024/pull/255
