### ISSUE TITLE
Issueテンプレートの「政策ビジョン」部分の変更

### ISSUE THREAD

**Issue by RyutaroHashimoto** [takahiroanno2024/election2024#152]
# WHY
- 政策カテゴリを選択式にしてlistで記述しているため、github上でTaskとして認識されてしまっている
![Screenshot 2024-06-24 at 3 21 53](https://github.com/takahiroanno2024/election2024/assets/43675716/a66cd713-b116-4ac7-bf41-495c974febf6)
- 多くのissueは作られているが、それが現時点でどういう状態や段階にあるかが不明確

# WHAT
- [ ] 政策カテゴリの入力をテンプレートから削除するかどうか議論
  - Github ActionsでGPTで自動でLabelが追加されているため、削除しても問題ないと考えられる
- [ ] 新たにstatusのセクションを追加するかどうか議論する
  - 下記のような例が考えられる
      - 議題作成
      - 参考情報調査
      - アクションプラン決定
 

# RESOURCE
- https://docs.github.com/ja/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

**Comment by masatosasano2** [comment]
1点目については、入れ違いで以下の変更により解消していると思われます。
https://github.com/takahiroanno2024/election2024/pull/138

**Comment by TakatsuguImaizumi** [comment]
こちらはテンプレート改善で解消した認識ですので、closeさせて頂きます！ご指摘いただきありがとうございました！
