### ISSUE TITLE
著作権者表記に関して

### ISSUE THREAD

**Issue by oageo** [takahiroanno2024/election2024#174]
公式サイトにおける連絡先がメディア向けでしたので、こちらで失礼いたします。

本リポジトリのREADMEを拝読させていただいたのですが、著作権者は安野様としての表記が求められております。しかしながら安野様以外の方が提案したものについてPRが受け付けられた後（安野様以外の著作物が追加された後）、このマニフェストは共同著作物となるかと思いますが、著作権者は安野様のみという表記になってしまっています。
そのため以下のような形で修正を行う必要があるのではないでしょうか。

* 「安野様と貢献者」スタイルで表記する
    * 例えば日本語版Wikipediaでは「ウィキペディアの執筆者」という名義が著作権者として用いられています。
* 著作権者表記はそのままに、PR時に著作権の譲渡等について同意していただく
    * 著作権者表記は現状の「安野たかひろ」のまま、今後のPR時に著作権者の表記/著作権の譲渡等について同意を求める方式です。
    * こちらの方が現実的かと思います。

著作権者の表記について理解不足がありましたらご指摘ください。個人的には都知事選におけるマニフェストをGitHub上で公開し、PRを受け付けるという試みは非常に面白いと思っています。今後の事例の参考となるためにも検討していただきますと幸いです。

**Comment by TakatsuguImaizumi** [comment]
ありがとうございます。疑問はもっともかと思います。

共同著作権者であるコントリビューターの著作権表示については、①CONTRIBUTORSファイルに記載する方法、②LICENSEファイルに記載する方法、③コミットメッセージやPRの履歴を通じて特定できるので省略する方法などがあり、今回は③を採用しております。
利用者に明示していただくのは、代表者としての安野貴博の名前のみとなります。

なお、READMEにおいて `「貢献者は、本リポジトリをクリエイティブ・コモンズ・ライセンスのCC-BY-4.0として第三者が利用することに同意したものとみなします。」` と記載させていただいているため、明示的に著作権を譲渡頂かなくても、本リポジトリについて個別のコントリビューターが著作権に基づく使用等の差し止めはできないこととしております。

**Comment by oageo** [comment]
ご回答ありがとうございます。手法を理解しました。ただコミットログを参照するという方法は必ずしも一般的ではないかと思いますので、README等に示すべきではないでしょうか…？

**Comment by TakatsuguImaizumi** [comment]
@oageo 
ありがとうございます。

> 貢献者の著作権者表記についてはコミットログ等をもって代えさせていただきます。

といった一文を挿入することを検討していますが、こちらで違和感ありませんでしょうか？

**Comment by oageo** [comment]
ありがとうございます。（マニフェストを改善している方々が同意すれば、ですが）そちらで問題はないかと思います。

ただ、（README等に示すべき、と言及した手前申し訳ないのですが）そういった文言をREADMEのみではなく、以下に示すようなPRテンプレートにおけるチェックボックス等の形でも追加するべきかと思います。そのようにすると後から問題になることが防げるかと存じます。ご検討いただけますと幸いです。

------
- [ ] 私は帰属表示を本リポジトリのコミットログで示すことに同意します

**Comment by TakatsuguImaizumi** [comment]
@oageo ありがとうございます！

著作権者表記（CONTRIBUTORSファイルを作成するか、省略するか等）に関しては、メンテナが裁量的に決定することが多いようですので、そのような処理について個別にコントリビューターの同意が必要とまでは言えないのではないかと思います。
懸念されているのは「貢献者が共同著作者として名を連ねるよう主張することによるトラブル」かと思いますが、その気になれば [All Contributors](https://allcontributors.org/) のようなツールでリストアップすることもできますし、今回は不特定多数が参加するプロジェクトですので、できるだけ貢献に対するハードルや同意事項はなくす方向で運用したいと考えています。

我々も勉強になりました。ご指摘いただきありがとうございます！

**Comment by oageo** [comment]
こちらこそ、突然の質問にご対応いただきありがとうございます！

**Comment by oageo** [comment]
> > 貢献者の著作権者表記についてはコミットログ等をもって代えさせていただきます。
> といった一文を挿入することを検討していますが、こちらで違和感ありませんでしょうか？

こちら当方でPRを出したほうが良いでしょうか？

**Comment by TakatsuguImaizumi** [comment]
@oageo 本日対応するつもりでしたが、出して頂けると大変ありがたいです！

**Comment by oageo** [comment]
PR #203 を出しましたので、よしなに確認していただければと存じます。よろしくお願いいたします。
