### ISSUE TITLE
取組内容に対する予算とその実行計画及び体制を提示してほしい

### ISSUE THREAD

**Issue by Koichi-Ikebukuro** [takahiroanno2024/election2024#180]
### 政策ビジョン

行政

### 政策

マニフェストで掲げている課題に対するそれぞれの取組内容に対して、どのタイミングでどれくらいの予算を注ぎ込むのかを提示してほしい。可能であれば、どういった体制で実行するかまで提示してほしい。

### 必要だと思ったきっかけ

マニフェストでかげていることを実現するためには、「ヒト」「カネ」「時間」が必要であるが、それがマニフェストには明示されていないとわかったとき。

### なぜ必要か

マニフェストで掲げていることの実現性を示すことができるため。

### 調べたこと（裏付けとなる事実・ファクト）

マニフェスト
AIあんの

### 自由記述欄
AIあんのに質問すると何にどれくらいの予算をどのタイミングで使うかの回答は返って来るが、視覚的に捉えられるように資料化したほうが良いと思う。

_No response_

**Comment by Hanzo222** [comment]
https://x.gd/YU8G2
ReHacQの討論会でなぜか最初の4名だけ使用されたフォーマットが各課題の優先度と他の候補者との違いがわかりやすいと思いました。
特に全予算を100としてどの政策にどれだけ配分するか（リンク先ｐ.3）の作成をお願いしたいです。

**Comment by mu373** [comment]
Related: https://github.com/takahiroanno2024/election2024/issues/172
