### ISSUE TITLE
Issueに対応するラベルの追加

### ISSUE THREAD

**Issue by ogadra** [takahiroanno2024/election2024#198]
現在本リポジトリには、下記ラベルが追加されています。

- 医療・防災
- 教育・子育て
- 民主主義
- 経済
- 行政
- その他
  - こちらはマニフェスト提言テンプレートから選択できません。

一方でこのリポジトリには、 #186 や #189 など、リポジトリ自体に関するIssueが存在します。

GitHub Actionsなど、リポジトリのシステムに関するIssueに対応するラベルを追加し、システムに関するのIssueが分類できるようにしたいです。
ラベル名は `システム` などが良いのではないかと思います。

**Comment by TakatsuguImaizumi** [comment]
`システム関連` のラベルを作成しました！巡回して付与していきます！
