### ISSUE TITLE
男性に対する子宮頸がんワクチン接種の無償化に関して

### ISSUE THREAD

**Issue by ao1137** [takahiroanno2024/election2024#228]
### 政策ビジョン

医療・防災

### 政策

男性に対する子宮頸がんワクチン接種の無償化を行ってほしいです。

### 必要だと思ったきっかけ

子宮頸がんワクチンを打とうとしたとき女性は無償で打つことができるのに対して男性は有償であると知ったタイミングです。

### なぜ必要か

子宮頸がんは女性が発症するものであるが、男性・女性どちらもワクチン接種をすることで防げるものです。現在女性に対して子宮頸がんワクチン接種が無償で行われているのに対して、男性は費用が全額負担となっています。これは子宮頸がんを打とうとしている男性に対して打つハードルを作っていると思います。

### この Issue で議論したいこと

子宮頸がんワクチン接種に関して

### 調べたこと（裏付けとなる事実・ファクト）

- [東京都保険委員局がHPVワクチンの男性への接種について](https://www.hokeniryo.metro.tokyo.lg.jp/kansen/hpvdansei.html)
- [子宮頸がんの予防効果が高い9価HPVワクチンが公費で接種可能に](https://www.gov-online.go.jp/useful/article/202306/1.html)

**Comment by mu373** [comment]
イシュー作成ありがとうございます。問題提起に大いに賛同いたします。

HPVワクチンは女性の子宮頸がんのみならず、男性の肛門がん・中咽頭がん、尖圭コンジローマに対する予防効果が認められており、性別に関係なく接種を受けられる環境を整えることが重要であると考えています。既にアメリカ、オーストラリア、イギリス等では男性も公費接種の対象[1-3]となっていますが、日本では国レベルの定期接種化が見送られているのが現状です。

独自に助成を出す基礎自治体も増えてきていますが、東京都内でもそれは20区市町村に留まっており[4]、居住する場所によってワクチン接種へのアクセスに格差が開いてしまっていることが課題であると考えます。

東京都としては今年4月から、都内の自治体が助成する場合に費用の半額を都が補助する取り組みを開始していますが[5]、基礎自治体の対応方針に依存することに変わりはありません。

したがって現役世代の健康を守る取り組みの一つとして、男性のHPVワクチン任意接種に対して**都として全額助成を行う**ことを提案いたします。

- [1] 米CDC. HPV Vaccination Recommendations.
- https://www.cdc.gov/vaccines/vpd/hpv/hcp/recommendations.html
- [2] 英NHS. HPV vaccine. https://www.nhs.uk/vaccinations/hpv-vaccine/.
- [3] 豪Department of Health and Aged Care. HPV (human papillomavirus) vaccine. https://www.health.gov.au/topics/immunisation/vaccines/human-papillomavirus-hpv-immunisation-service
- [4] 東京都保健医療局. HPV男性接種 区市町村情報ページ. https://www.hokeniryo.metro.tokyo.lg.jp/kansen/hpvdansei_info.html
- [5] 東京新聞「HPVワクチン 男性も接種して 子宮頸がん予防だけじゃない 高い費用、助成する自治体も」https://www.tokyo-np.co.jp/article/311667

**Comment by mu373** [comment]
具体的に変更提案してみたところ、マニフェストに盛り込んでいただけました…！

**Comment by ao1137** [comment]
提案の具体化ありがとうございます！！！！
