### ISSUE TITLE
妊婦へのRSウイルスワクチンの公費助成

### ISSUE THREAD

**Issue by summersummer800** [takahiroanno2024/election2024#283]
### 政策ビジョン

医療・防災, 教育・子育て

### 政策

男性のHPVワクチン接種の助成について、マニフェストに追加いただいてありがとうございます。
公衆衛生に関する提案を受け入れて下さることが分かったため、もう一点、公費助成を提案したいワクチンがあります。

今年の6月から、RS ウイルス母子免疫ワクチン(アブリスボ)が接種可能になりました。
新生児のRSウイルス罹患による重症化を防ぐ事が期待できるワクチンで、妊婦さんが接種する事で、お腹の赤ちゃんに抗体移行します。
しかし現状では接種が任意で30,000円近くかかり、接種を躊躇する妊婦さんも多いと思います。
このため希望する妊婦が誰でも打てるよう、ぜひ公費助成の対象になって欲しいです。

### 必要だと思ったきっかけ

RSウイルスは、そこそこ大きくなった子供や大人にとっては、ちょっと咳がしつこい風邪程度で済みますが、赤ちゃん（特に生後6ヶ月までの乳児）が罹患すると重症化しやすく、呼吸困難になったり命に関わる場合もあります。
私の子供も、実際生後2ヶ月で罹患し、喘鳴・細気管支炎が認められたため10日間入院しました。
無事に回復したから良かったですが、生きた心地がしませんでした。

私とは別の方ですが、さらに重症化したケースをマンガでポストしてくださっている方もいます↓
https://x.com/odahirokoillust/status/1676757085596569600?s=46&t=9ehdwDrO4CSMnazP8KngEw

### なぜ必要か

先述の通り、現在は費用が30,000円〜かかり、接種のハードルが高いです。
これが助成されて無料になれば、「打てるなら打っておこう」と考える妊婦さんも増え、多くの赤ちゃんの命を救えると思います。

### この Issue で議論したいこと

まだ登場したばかりのワクチンなので色々ご意見あると思いますが、全額助成の是非など、建設的な議論ができればと思います。

### 調べたこと（裏付けとなる事実・ファクト）

小児科学会
https://www.jpeds.or.jp/modules/activity/index.php?content_id=559

産科婦人科学会
https://www.jsog.or.jp/news/pdf/20240627_ippan.pdf

現在のワクチン費用参考
https://www.moricli.jp/topics/2024/05/29/1385/

**Comment by summersummer800** [comment]
ワクチンの価格ですが、参考にしたクリニックの費用は診察費も含めたものだったので、30,000〜に訂正しました。

**Comment by TomeSelfcare** [comment]
この提案があげられたこと、めちゃくちゃ嬉しいです！ありがとうございます。
2歳目前に我が子が患い、父母共々なかなか症状重く、療養期間本当に大変でした。(親族も離れて暮らしているので頼らず。)
友人からも子供がRSで入院し、対処療法しかできずにとても苦労したと聞きました。
ぜひご検討いただきたいです。

**Comment by micthell712** [comment]
@summersummer800 ご提案ありがとうございます！
もしよろしければ、教育・子育て分野でプルリクエストを出していただけないでしょうか？

**Comment by summersummer800** [comment]
@micthell712 
ご返信ありがとうございます。マニフェストにプルリクエストを出してみました。
同意してくださる方が多くうれしいです。
よろしくお願いします。

**Comment by takahiroanno** [comment]
@summersummer800 
ありがとうございます。私が見落としているかもしれないのですが、Pull Requestの番号やURLいただけますでしょうか？

**Comment by summersummer800** [comment]
@takahiroanno 
ご連絡ありがとうございます。
申し訳ありません。プルリクが初めてだったのでうまく登録できていなかったようです。
再度登録してみましたが、こちらでいかがでしょうか。
https://github.com/takahiroanno2024/election2024/pull/293#issue-2389781600
ご検討いただけると幸いです。

**Comment by summersummer800** [comment]
マニフェストに反映いただき、ありがとうございます！
イシューを立ててから24時間も経たないうちに検討が進み、驚きました。
ありがとうございました。
