### ISSUE TITLE
「子育てにかかる経済的負担への支援をより手厚く」の対象範囲の拡大

### ISSUE THREAD

**Issue by zaq1tomo** [takahiroanno2024/election2024#32]
## 政策ビジョン

- [ ] 経済
- [ ] 医療・防災
- [x] 教育・子育て
- [ ] 行政
- [ ] 民主主義

## 政策

- 「[子育てにかかる経済的負担への支援をより手厚く](子育てにかかる経済的負担への支援をより手厚く
)」の対象範囲の拡大
- 具体的には、
  - 保育料の無償化を第一子まで拡大（小池百合子氏公約参照）
  - 雇用形態に依らない産休/育休の整備
  - すべての子育て世帯への一律補助
  - など

### なぜ必要か

- 自身が第一子出産を控えているが、現状案は対象家庭が限定的であり、対象に当たるか不確かなため

### このイシューで議論したいこと

- 上記案の妥当性及びより良い支援案など

### 調べたこと（裏付けとなる事実・ファクト）

- 現状案

> - 住まいの費用
>     - 既存政策では40歳代までの夫婦世帯の方に対して、市部の一部空家を対象に、入居から3年間、毎月の家賃を20％割引している。（JKK東京｜ペアさぽ）
>     - 我々の提案は、その優遇期間を第一子義務教育修了年限まで拡大
> - 教育費用
>     - 既存政策では中学3年生・高校3年生（またはこれに準ずる者）を対象に塾費用や受験料の無利子での貸付
>         - 東京都社会福祉協議会による受験生チャレンジ支援貸付事業
>     - 我々の提案は、所得制限に応じて、貸与から給付へ転換すること

- [小池百合子氏、保育無償化を拡大　都知事3選へ公約発表 - 日本経済新聞 ](https://www.nikkei.com/article/DGXZQOCC178C10X10C24A6000000/)

**Comment by mactkg** [comment]
私は今週娘が誕生しましたが、妻がフリーランスで産休・育休の制度がなく、自分で貯蓄、やりくりすることが必要になりました。
一方会社員（私もですが）は育休制度があり、不平等感を感じます。
多様な働き方があり得る世の中で、サポートの対象範囲の拡大は合わせて必要ではないでしょうか。

**Comment by zaq1tomo** [comment]
@mactkg さん、コメントありがとうございます。フリーランスの産休や育休の問題について共感いたします。多様な働き方が推進される昨今、雇用形態に関わらず産休や育休の整備も必要だと感じます。

**Comment by sasaharukimedes** [comment]
出産・子育てに際して、公平に補助や支援を受けられるべきであると思います。

働き方が多様になっているのに、それを想定した法制度や支援制度になっていないことは、結婚や出産、子育てと長期に渡る人生設計の足かせになっているのは、事実としてあると思います。
