### ISSUE TITLE
🧹  経済 - 誤字の修正

### ISSUE THREAD

**Issue by EG-easy** [takahiroanno2024/election2024#36]
## Overview

* 爆増 -> 倍増に修正
![image](https://github.com/takahiroanno2024/election2024/assets/35296935/cd4715f9-92de-4644-ab5d-b2fa49142369)

## Tasks
- スライド内および他の箇所で"倍増"と使われていたので、"爆増"から"倍増"に変更して統一しました

**Comment by kawayuta** [comment]
ニュアンスが大きく変わりますが以下の点から維持で良いかと。

三省堂国語辞典は７版（2014年）から「爆」という項目を置いており、８版（22年）でも踏襲されています。俗用と断りながら、造語成分として語頭に付き「激しく。たいへん」という意味を添えると説明しており、用例には「爆売れ・爆食い・爆安・爆増」とあります。

三国８版は見出し語としても「爆上げ、爆食、爆睡、爆速、爆誕、爆釣、爆騰」といった語を採録しており、いずれも程度の甚だしさを示す「爆」の例です。

**Comment by EG-easy** [comment]
@kawayuta 

コメント、ありがとうございます！

辞書的意味として「倍増」、「爆増」の区別は今回どちらでもあり得ると考えているのですが、スライド内の画像で「所得倍増」と書かれているのでそちらに揃えたほうが合理的かなというissueでした！

あえて文章中のタイトルで「爆増」、スライド中で「倍増」と使い分けている意図があるようでしたらこちらのissueは取り下げたいと思います。

**Comment by munierujp** [comment]
「倍増」だと2倍という意味になるので、実際にどの程度の増加を目指すのかにもよるかと思います。

>［名］(スル)2倍にふえること。2倍にふやすこと。倍まし。「売り上げが—する」

https://dictionary.goo.ne.jp/word/%E5%80%8D%E5%A2%97/
