### ISSUE TITLE
これからの感染症対応

### ISSUE THREAD

**Issue by dmikurube** [takahiroanno2024/election2024#6]
## 政策ビジョン

- [ ] 経済
- [X] 医療・防災
- [ ] 教育・子育て
- [ ] 行政
- [ ] 民主主義

## 政策

新型コロナウィルス、およびそれ以外の新たにやってくる感染症への対応。

### 必要だと思ったきっかけ

新型コロナウィルス対応については国の分類こそ変わりましたが、今も新しい変異とともに COVID の流行は続き、特にこの 2 〜 3 週間で再び拡大が始まりつつあるようです。また、報道もされている溶連菌や、徐々に人類に近づいている鳥インフルエンザなど、残念なことに感染症の危機はまだ過ぎ去っていないようです。

### なぜ必要か

高齢者でない若者にも基礎疾患等を抱える人は常に一定数おり、特にそのような人にとって COVID-19 やその他の感染症は今でも脅威で、いまでも特に混雑しやすい東京の公共交通機関などは、乗ることも躊躇してできるだけ避けるような状態です。

また、健康な若者であっても、何度も COVID に罹患しているとそのたびに重症化率も後遺症率、また梗塞や心疾患などの割合も上がる、ということが国外の事例などからわかってきています。ひどくなれば働けない・動けない状態が数ヶ月〜年単位で続く後遺症になる例が、若者でも無視できない程度に既に起きているようです。

### このイシューで議論したいこと

足元の COVID や溶連菌、さらに新しく来る可能性のある鳥インフルエンザなどの新規感染症に対して、基礎疾患を持った人や後遺症を患った人を「誰も取り残さない」ための政策の必要性の有無、およびその具体的な政策。

### 調べたこと（裏付けとなる事実・ファクト）

* https://www.nhk.or.jp/maebashi/lreport/article/001/31/
* https://www.thelancet.com/journals/lanepe/article/PIIS2666-7762(23)00221-1/fulltext
* https://www150.statcan.gc.ca/n1/pub/75-006-x/2023001/article/00015-eng.htm
* https://www.today.com/health/covid-heart-attack-young-people-rcna69903

**Comment by dmikurube** [comment]
ブロードリスニングということで出馬表明直後に公開された Web フォームに、およそ ↑ のような意見・質問を書いて送ったのですが、マニフェストの詳細版 ver.1 では感染症について一言も触れられていませんでした。基礎疾患を持つ人のような少数者はブロードリスニングからも取り残される、と示唆するようで、そこはとても残念に思っていました。

しかしこれで終わらせてしまわないように、今後に期待して、こちらに公開で投稿させていただきました。そしてこの GitHub Issues は政策に対する「リクエスト」ということなので、主な Issue Description は政策の必要性の議論としつつ、このコメントでもう少し具体的なリクエストを。

(個人的なリクエストとして本音を言えば「感染流行期における、特に東京都交通局の公共交通機関での、マスク着用の推奨」くらいはしてほしいと思っています。強制は法的にできないと思いますが、「推奨」すらできない理由は見当たりません。しかしそれでもこれはおそらく多くの反発も生む意見でしょうから、いったんは脇において、ここではまずそれより手前の提案です。(マスクのような紛糾しそうなトピックを「ブロードリスニング」したときに、どのような対応をされるのか、というのも個人的には見てみたいですが。))

-----

「感染流行期における」対応をしようにも、それ以前に現状では、取るべきデータが端的に不足している、と言われています。一部医療機関における定点観測こそされていますが、リアルタイム性に欠け、検査の有料化にともなって罹患しても検査を受けない人が増え、実情を捉えたデータになっていない疑いが強いです。そしてデータとして「感染流行期」を把握できないから、公にもほぼ対策を取らない、という状態が恒常化してしまいました。

さて、ソフトウェア・エンジニアリングの定石には、最適化や高速化にあたって「[推測するな、計測せよ](https://logmi.jp/tech/articles/329163)」というものがあります。データが不足したままに推測で公として対策を打つのはもちろん難しいでしょうし、適切ではないかもしれません。しかしデータが不足したなかで「『何も起きていないだろう』という『推測』」をもとに「『何もしないという施策』を『選ぶ』」のもまた、正しいとは思えません。

そこでこれは、まずは「テクノロジーの力で」もう少し信頼できる包括的なデータを取る・取り続ける、そして発信する、という対策をまずは確実に、という提案です。

いくつか例を挙げます。

* 隣の神奈川県では、相模川流域において下水中の新型コロナウィルス量を計る、という計測が続けられています。これは、感染者の実数に対してほぼ定数コストで実施・継続できる計測ですので、まずはこのような観測を都として始めてほしいと考えています。
  * https://www.pref.kanagawa.jp/docs/h2d/covid19/past_sewer/202311graph.html
  * 実は東京都でも以前は実施されていたのですが、終了してしまいました。
* 安野さんが指導を受けた松尾先生からそう離れていないであろう東大の生産研でも、「X (旧 Twitter) のポストから感染状況を推定する」という研究がおこなわれていました。これもまさに「ブロードリスニング」の例であると思いますが、このような計測手法を都として支援していくことも考えられるのではないでしょうか。
  * https://www.tkl.iis.u-tokyo.ac.jp/~toyoda/covid19/
  * こちらも残念ながら昨年度いっぱいで終了されてしまいましたが。
  * https://x.com/toyodam/status/1774688184460583373
* Audrey Tang 氏の拠点である台湾では、検査キットの無料配布などの対応を、今の流行に対してもおこなっているそうです。台湾はコロナ禍の初期から、 Audrey 氏のデジタル施策も含めて対応の速さと的確さで知られていましたね。
  * https://tw.news.yahoo.com/taiwan-distribute-3m-free-covid-115106585.html

個人の声を LLM など用いて「リスニング」するのももちろん大事ですが、「テクノロジーの力で」広く客観的に「リスニング」できる、古典的なデータ収集方法や施策も既に数多くあります。そのような施策をわざわざ捨てる理由はありませんし、検討に値するのではないかと思います。

**Comment by hotter22** [comment]
命に関わるデマも多かったので、情報汚染/情報公害 を一方的に拡散されぬ様「両論併記」の広報活動も欲しいです

**Comment by kuippa** [comment]
東京はこの２０年ぐらいで白昼町中でネズミを平然とみかけるようになりました。都市に緩衝帯を設けず、雨水と下水が合流方式のままなので、どこまでも無尽蔵にひろがってしまっています。

コロナをはじめ多くの病気は人獣共通感染症なので、基本的には人間だけの行動を制限しても解決しないことが多いです。

ペストコントロールをおこない衛生害虫の認知状況などについては調査結果をオープンデータ化し、下水のウイルスサーベイランスをはじめ、都市計画の評価指標として盛り込んでほしいですね。
情報がなければ都民もなんとなくでしかわかりませんし。

**Comment by nishio** [comment]
>マスクのような紛糾しそうなトピックを「ブロードリスニング」したときに、どのような対応をされるのか、というのも個人的には見てみたい

ここは同感で、オープンな議論が可能な場を作る必要があると考えており、個人的に台湾政府の合意形成プラットフォームvTaiwanで使われていたPolisのインスタンスを立てました(昨日やっと動いたところ)

https://polis.nhiro.org/6kvuuursmy
>選挙ポスターに対する議論
>選挙ポスターに関するTwitter(X)上の議論を見てAI(Claude 3.5 Sonnet)が意見のリストを作りました。みなさんは賛成反対を投じることができます。
>投票内容は個人が特定されない形でオープンデータにする予定です。

ちょっとまだ解説を書くとこまで手が回ってませんが、10~20件の賛否が分かれそうな意見のリストとタイトルと解説を作ってもらえればこちらで代わりに作ることは可能です。(自分でアカウントを作って自分で作るのも可能だとは思います)

**Comment by dmikurube** [comment]
そうして議論をできる場、そしてそれを作る、というのもそれはそれで (主に長期的には) 意味のある話だし、それが悪いという話ではもちろんないんですが (上のポスターに対する議論にはちょっと意見を投げました)

しかし選挙で選挙人が支持者を決めようと文脈においては、「で、立候補したあなたは、これやってくれる気あるの、ないの、どっちなの」としかならないんですよねえ…。

**Comment by nishio** [comment]
>選挙で選挙人が支持者を決めようと文脈においては、「で、立候補したあなたは、これやってくれる気あるの、ないの、どっちなの」としかならないんですよねえ…。

このスレッドではあなた個人の投票方針に関する意見はオフトピックだと思います。でも、別途この議論のissueを立ててもいいかもですね。

**Comment by dmikurube** [comment]
それはそう。ただこの Issue は提案・リクエストの場だとも理解しているので (マスクについては自分でオフトピックにしていますが) 「で、結局やってくれるのこれ」っていう点に対する反応は (ここじゃなくて演説とか Twitter とか YouTube とかなんでもいいから) 欲しいというのが、提案した者としての正直な気持ちですよね。

提案上げさせるだけ上げさせて終わり、にはならないことを期待しています。

**Comment by nishio** [comment]
>Issue は提案・リクエストの場だとも理解しているので

その解釈が正しいかどうかはちょっと疑問ですね。提案はPullReqであり、やるかどうかの意思決定はマージかリジェクトかで表明されるという解釈を僕はしていました。

**Comment by nishio** [comment]
>この Issue くらい新しい提案 (ベースのマニフェストを大きく変えるレベルの) を取り込む気は実質的にないんだな、と私は解釈しました。

その解釈は正しくないと思います...

**Comment by nishio** [comment]
> 調査結果をオープンデータ化し、下水のウイルスサーベイランスをはじめ、都市計画の評価指標として盛り込んでほしいですね。

「下水のウイルスサーベイランスをオープンデータ化する」は多分コストがあまりかからないし十分具体的なので実行可能度の高い施策だなと思いました

**Comment by dmikurube** [comment]
オープンソースのプロジェクトのメンテナーなどを実際にやったことがあればわかると思いますが、いきなりポッと来た人に pull request を出されても、たいていは「やってほしいことはわかった、でもそこじゃない・そうじゃない」っていうことばかりなんですよ。

ここでもそれはたぶん同じで、この提案を pull request にするにしても、

* どこの章にどういう文で入れるのか?
* 挙げた実例の中のどれを入れてどれを入れないのか?
* 素直に【医療・防災】の枠に入れるとしても、安野さんのマニフェストだと【医療・防災】は「先輩世代」のものだ、って言っています。ただこの Issue で、私は『感染症対策は「先輩世代」だけのものではない (基礎疾患も後遺症も)』と言っています。なので【医療・防災】を「先輩世代」のものとするところから根本的に書き換えてほしいが、そのためには全体の話の流れをどうするのか?

など考えることはいくつもありますが、最終的にどういう形にするか決めるのは、マニフェストの owner である安野さんでなければならないわけです。

そういうところを、いきなり pull request にされてもふつう owner は困るので、議論するために issue があって、いろいろ issue で議論した上で「じゃあこれをこういう方向で {owner が pull request にします | 起案者が pull request にしてください}」という話になるのが、いわゆる一般的な「オープンソース文化」におけるプロセスです。

そこで「Issue は提案・リクエストの場」というところから否定されてしまうと、「そもそも入れる気ないじゃん…」という解釈になってもしかたがないかと思います。

owner の安野さんは演説で飛び回っていてお忙しいのは理解できるのですが、とりあえず issue での議論にもある程度は入ってきてもらわないと話が始まらないし、結果的に「提案上げさせるだけ上げさせて終わり」になってしまうのだろうなと思います。

**Comment by jene8774** [comment]
とても興味深くて面白いですね。俺たちがこうやって実験の場であるgithubにいろいろ書きこむことで、
実際のブロードリスニングというものの問題点や整備点が浮き上がってくる。
そういう意味ではこのgithubはすでに価値があるのかもしれないですね。

一番我々が頭に入れておく必要があるのは、6月25日現時点ではここを開設してくれた安野たかひろさんは東京都知事ではないということです。ここはあくまでまだいち候補者の実験の場であるということです。
正式なものではないので、自分の書いた意見が東京都に通るというわけではないし、開設した安野さんも返答をする政治的な義務はないということです。

安野さん、当選されるといいですね。
あるいはほかの候補者の方も、民意の再確認をもってしかるべき方が都知事に当選されるといいですね。

**Comment by dmikurube** [comment]
それはもちろん。ただ、意見を取り込むなり議論に実際に参加するなりの姿勢を見せられるかどうか、も、各有権者が安野さんを支持するかどうかを決める指標にもなるでしょう。

**Comment by nishio** [comment]
@dmikurube トップページのREADMEを読んでください

>課題提起（Issue・イシュー）
>東京都の政策や安野たかひろのマニフェストについて、直した方がいいところや追加した方がいいと思うことについて議論します。

>変更提案（Pull Request・プルリクエスト）
>安野たかひろのマニフェストに対して、具体的に変更提案します。


三廻部さんは"いきなり pull request にされてもふつう owner は困る"、"いろいろ issue で議論した上で「じゃあこれをこういう方向で {owner が pull request にします、または、起案者が pull request にしてください}」という話になるのが、いわゆる一般的な「オープンソース文化」におけるプロセスです。"と書いています。
READMEにも同様にIssueは議論の場、Pull Requestが具体的な提案の手段、と書かれているように思います。

意見は食い違っていないように思うのに、なぜ"「Issue は提案・リクエストの場」というところから否定されてしまうと..."というネガティブな感情を持たれているのかよくわかりません。

**Comment by dmikurube** [comment]
「ここをこうして入れるのはどうでしょう」などの実際にマニフェストに入れてもらうための議論、または否定的なものであっても「これはこういう理由で入れられません」などの議論さえ、いつになったら始められるのかがまったく見えない、というのがネガティブな理由ですね。

**Comment by nishio** [comment]
>議論...いつになったら始められるのかがまったく見えない

始まっているのでは？と思ったのですが、もしかして

>最終的にどういう形にするか決めるのは、マニフェストの owner である安野さんでなければならない

>owner の安野さんは演説で飛び回っていてお忙しいのは理解できるのですが、とりあえず issue での議論にもある程度は入ってきてもらわないと話が始まらない

というあたりから推測すると、安野さんが直接自分と会話しなければ「議論」だとみなさないということなのでしょうか...？

**Comment by dmikurube** [comment]
別にそれ以前の議論も議論ではあると思いますが、ここが安野さんのマニフェストに対する議論の場である以上、当人が議論に入らなければ始まらないのでは。

いや、安野さんのマニフェスト関係なく、みんなが好き勝手なことを言い合うだけの場です、ということなら別にそれでもいいのですが。

**Comment by nishio** [comment]
>当人が議論に入らなければ始まらないのでは。

なるほどなるほど、ボタンのかけ違いの理由が理解できました。
建設的な提案の形にまとめるとこんな感じかなと思います:

1. 「政策立案チームがどのように動いてマニフェストの更新につなげていくか」の説明がREADMEにないので、自分の立てたissueがその後どうなっていくのかわからない、きちんと言語化して解説すべきだ

この提案には異論はないです。やっていくべきですね。

一方で "安野さんが直接自分と会話しなければ「議論」ではない" というスタイルの運営は、スケーラビリティが低くて現実的に実行可能ではないので、そういうスタイルだと思われているのは誤解です。Linux開発のすべてのIssuesでLinusが議論に参加するわけではないのと同じです。

**Comment by dmikurube** [comment]
> 「政策立案チームがどのように動いてマニフェストの更新につなげていくか」の説明がREADMEにないので、自分の立てたissueがその後どうなっていくのかわからない、きちんと言語化して解説すべきだ

そうですね、そこがしっかりしていれば異論はないです。

> Linux開発のすべてのIssuesでLinusが議論に参加するわけではない

ただ、これはけっこう参加してるはずですよ。少なくとも「 Linus がいっさい関知していないコードがメインラインの Linus tree に入る」ことはたぶんないです。

**Comment by dmikurube** [comment]
GitHub 的に言えば ISSUE_TEMPLATE.md 以外に CONTRIBUTING.md がしっかり書いてあるといいんじゃないでしょうか。

**Comment by dmikurube** [comment]
オフトピックの一般論なんですが、オープンソースのプロジェクトにおいて、なぜ「[優しい終身の独裁者](https://ja.wikipedia.org/wiki/%E5%84%AA%E3%81%97%E3%81%84%E7%B5%82%E8%BA%AB%E3%81%AE%E7%8B%AC%E8%A3%81%E8%80%85)」というあり方が比較的ポピュラーなのか、逆に「優しい終身の独裁者がいないオープンソース・プロジェクトの運営」のガバナンスを構築するのがどれほど難しいのか、というあたりについて考えてみると、まあちょっとおもしろいんじゃないでしょうか。

参考:
* https://xtech.nikkei.com/atcl/nxt/column/18/00818/062100007/
* https://www.pythonic-exam.com/archives/6989

…と、あるオープンソース・プロジェクトで実質的な「優しい終身の独裁者」のメンテナーをやっている立場から、どうにか平和的に降りる筋道を探して苦心している、いちエンジニアからは申し上げておきます…。

**Comment by wchan1229** [comment]
東京都としてできることには、新たな感染症対応人材の育成支援、ワクチン接種費用の都独自の補助上乗せ、コロナ後遺症医療提供病院のさらなる拡大を推進していくことなどがあるのではないかと思います。

**Comment by dmikurube** [comment]
#220 のコメントをもとに reopen しようと思ったのですが、私には reopen する権限が無いようでしたので、コメントを残しておきます。
