### ISSUE TITLE
安野氏のアピアランス改善

### ISSUE THREAD

**Issue by makepaym** [takahiroanno2024/election2024#70]
## 政策ビジョン

- [ ] 経済
- [ ] 医療・防災
- [ ] 教育・子育て
- [ ] 行政
- [ ✔︎ ] 民主主義

## 政策

・安野氏のアピアランス改善を行う

### 必要だと思ったきっかけ

・民主主義社会においてはアピアランス等も重要視する者があることtweetが指摘していたhttps://x.com/sgee30418056/status/1804167831296315799

### なぜ必要か

・政策の実現に向け、様々な価値判断の基準を持つ東京都民からできる限り受容いただける可能性を高め、当選するため。

### このイシューで議論したいこと

・見た目へのこだわりがある、どのアピアランスであってもその中身が尊重されるべきだと考えられている場合は、本イシューを放念ください。

### 調べたこと（裏付けとなる事実・ファクト）

・https://www.kantei.go.jp/jp/rekidainaikaku/index.html

**Comment by tomoto3** [comment]
今回の都議会選挙では、掲示板ジャック、単なる売名目的、あるいはビジネス目的で立候補している候補者が多く、民主主義の危機を感じる。安野氏のように真剣に東京都行政の現在と未来を詰めてきている候補者が埋もれてしまう。一方、現職候補や知名度が高い候補、あるいは政党が推薦している候補は、既存メディア（TVや新聞）へのアピアランスが多く、有権者にリーチしやすい。こうなってくると、政党政治との繋がりを持たない安野氏のような候補は極めて不利な立場に置かれる。

若手の政治家が成功するには、話題性と資金力が重要だと思う。残念なことだが、ある程度は政党や政治団体との繋がりを構築していくのもやむを得ないと思われる。

**Comment by br3kyokyo** [comment]
髪型や服装の否定はアイデンティティの否定に繋がるものであり、選挙以前の問題だと思うので、これは安野さんの自由意志だと思います。

そもそも見た目は政策には関係ないと思うので。個人的には何も問題ないと思います。

安野さんが納得して良いなら良いと思うのですが、仮に当選のためにアイデンティティを曲げる必要まであるのであれば、それが社会の総意だということでありますし、代表としてそこまでする必要はないように思います。むしろそこを曲げずに選挙に臨むことが問題提起にもなる気がします。

**Comment by makepaym** [comment]
話題の投稿について追加
https://x.com/kanazawa_you/status/1804141298590585155?s=46

政治家はネコがやればいいと言う人がいましたが、興味関心のあるなし、なんとなく好き嫌い、などいろんな価値尺度がある中で現在の日本東京都の社会全体から見た大体のそれっぽさはあっても良いのかもねくらいの気持ちでイシュー投げました。安野さんの自己表現の領域を侵害するつもりは全くございません。あくまで目標達成への確度上げのツールとして容認できるかの話になります。安野さんの掲げるソーシャルリスニングの観点からも、これは小賢しくて嫌われているマーケティングではなく、今この地域のみなさんに受け入れられるための、効果の高い取り組みとなる気がいたします。

以上

以下ソーシャルリスニングの参考
（「安野さん」で最新のもの）

肯定

インサイト：
・政治に割合興味のない女性からの支持獲得において障壁となっている可能性はある（興味ないけど若くて頑張ってるね感の視覚からの獲得）

https://x.com/okdwitw/status/1804410996154618096?s=46

https://x.com/behemuhemulove/status/1804408548761252152?s=46

https://x.com/monroe_________/status/1804404228577989047?s=46

https://x.com/rim_northscale/status/1804385544874659881?s=46

https://x.com/forestaro_tw/status/1804381729500667981?s=46

https://x.com/virtus256/status/1804380218687394234?s=46

https://x.com/funekaz/status/1804362587955401167?s=46

https://x.com/samayou_banker/status/1804361389311693308?s=46

https://x.com/gaming_kumasan/status/1804351689996275744?s=46

https://x.com/white_boards/status/1804351448341160084?s=46

https://x.com/shingeki_epica/status/1804350918730620943?s=46

https://x.com/tokagenokage/status/1804345886379774427?s=46

否定
インサイト：
・見た目で判断されない社会へのコミットと受け取られており、一定の支持も

https://x.com/funamushi2784/status/1804418343694131349?s=46

https://x.com/waitiaw108/status/1804388096953516093?s=46

https://x.com/lapintokyo/status/1804383397038743977?s=46

https://x.com/zero_kpr/status/1804373379891499318?s=46

https://x.com/binbouhimanasi9/status/1804354588188787002?s=46

通信欄：tomoto3さん・br3kyokyoさん、何か勘違いをされているようです。

**Comment by br3kyokyo** [comment]
@makepaym 見た目についての話題が向こうのissueで出ていて、こちらに移した方が良いという意味でメンションしたつもりなのですが、勘違いなどあったらご指摘ください🙇

**Comment by makepaym** [comment]
@br3kyokyo さん、メンション先最後まで確認しました。見た目についての話題はこちらで良いと思います。お手数おかけします。

**Comment by makepaym** [comment]
（（完全に脱線しますが）もしかするとこれは、クライアントが1,400万の東京都民であること、当選後の地位が東京都知事であること、これが今までの安野さんの環境と異なりますが対応可能ですかという転職の面接にあたり、安野さんがどれくらい自分を適応させるかのお話なんじゃないでしょうか。ちょっと今しがた放送されていたYoutube Liveを見ていてもオファーに辿り着くような気がいたしません…それはほのぼのとした、事情通に向けた会話なのです。いくつかの人が話すように、専門性を活かし、都知事以外の形で都政に貢献される方が良いのかも知れません。）

**Comment by br3kyokyo** [comment]
https://x.com/n_katamari/status/1804372718130991241?s=46&t=lMNf_ULI7YQKyuYMSSXqRg

ブロックは良くない気がします。

**Comment by br3kyokyo** [comment]
クローズされたissueですが、Twitterでブロックを行うのは良くないと思います。対話と議論を行う以上、ミュートはあってもブロックは基本的に行わない方が良いように思います。

**Comment by yasamosa** [comment]
個性としてのアピアランスも大事ですが、選挙に勝つためのアピアランスは何が良いのか、を考えるべきかと。
実際に投票所に通う層に刺さるもにはどう言ったものなのか。
少なくとも私は、終盤戦の今だからこそ、容姿を整えて最後のお願いをすると、響く人も少なくないと考えます。

以下、選挙おける容姿の研究の事例です。
ChatGPTに要約させました。

「Facial Competence in Presidential Elections」

研究者: Alexander Todorov 他
発表年: 2005年
概要: プリンストン大学のAlexander Todorov教授と彼のチームが行った研究。この研究では、顔の写真を見ただけで候補者の勝敗を予測する実験を行い、有権者が顔の「コンピテンス（能力感）」を基に候補者を評価することが示されました。
「The Impact of Candidate Appearance and Personality on Election Outcomes in Parliamentary Elections」

研究者: Anthony Evans, Jordi Sunyer, David T. Smith
発表年: 2018年
概要: イギリスの大学の研究チームによる研究で、候補者の見た目や性格が選挙結果に与える影響を分析しました。彼らは、候補者の外見が有権者の判断に大きな影響を与えることを示しています。
「The Role of Candidate Facial Appearance in Elections: Evidence from Russian Elections」

研究者: Igor Grossmann 他
発表年: 2013年
概要: ウォータールー大学のIgor Grossmann教授と彼のチームによる研究。ロシアの選挙を対象に、候補者の顔の外見が選挙結果にどのように影響するかを調査し、魅力的な顔の候補者がより多くの票を得る傾向があることを発見しました。
「Candidate Appearance and Electoral Success in Britain」

研究者: Andrew Leigh, Amy King
発表年: 2006年
概要: この研究では、イギリスの選挙において、候補者の見た目が選挙の成功にどのように影響するかを調査しました。研究結果は、魅力的な外見が有権者の投票行動に影響を与えることを示しています。
