### ISSUE TITLE
公的な情報発信用のWEBサイトやモバイルアプリに都政に対する意見表明への導線を追加してほしい

### ISSUE THREAD

**Issue by masatosasano2** [takahiroanno2024/election2024#8]
## 政策ビジョン
- [ ] 経済
- [ ] 医療・防災
- [ ] 教育・子育て
- [ ] 行政
- [x] 民主主義

## 政策
公的な情報発信を担うWEBサイトやアプリにブロードリスニングの入り口を追加する。
### 必要だと思ったきっかけ
公的情報の発信に対してフィードバックしてくても連絡先がわからない。
### なぜ必要か
[都民が都政に参加できる場づくり](https://github.com/takahiroanno2024/election2024/blob/main/docs/manifest/democracy.md#:~:text=%E2%91%A2-,%E9%83%BD%E6%B0%91%E3%81%8C%E9%83%BD%E6%94%BF%E3%81%AB%E5%8F%82%E5%8A%A0%E3%81%A7%E3%81%8D%E3%82%8B%E5%A0%B4%E3%81%A5%E3%81%8F%E3%82%8A,-%E9%83%BD%E6%B0%91%E5%8F%82%E5%8A%A0%E5%9E%8B) という、マニフェストにある課題に対する提案。
### このイシューで議論したいこと
都政への参加を促す手段として適切かどうか。
### 調べたこと（裏付けとなる事実・ファクト）
東京都財務局が運営する以下のサイトや
 - [都財政の見える化ボード](https://www.zaimu.metro.tokyo.lg.jp/zaisei/zaisei/dashboard)
 - [My TOKYO](https://www.my.metro.tokyo.lg.jp/top)

公的情報を発信する以下のアプリには
 - [東京都防災アプリ](https://play.google.com/store/apps/details?id=jp.tokyo.metro.tokyotobousaiapp)
 - [ごみ分別アプリ さんあ〜る](https://play.google.com/store/apps/details?id=jp.co.delight_system.threeR.android&hl=ja)

参加型予算編成の情報を含め、都政の改善のためのフィードバック先の情報がない、または簡単に見つけられない。

**Comment by masatosasano2** [comment]
#9

**Comment by nishio** [comment]
今回、安野さんはTwitterやGitHubを使っていない人向けにGoogle Formでも情報を集めていて、即座自動的にオープンデータ化することをおこなっています。公的な情報発信を担うWEBサイトにこういうフォームへの入り口を追加するのは既存のWEBサイトにとっても大した追加コストなしに一歩前進できていいかもですね。


https://docs.google.com/forms/d/e/1FAIpQLSfiSmvhVjzW_POtep_8J53n1QRR3zc2QBtyqPPMQxfnzjmRyA/viewform

**Comment by masatosasano2** [comment]
対応する以下のpull request をマージいただいたので、解決済みとしてcloseします。
https://github.com/takahiroanno2024/election2024/pull/9
