### ISSUE TITLE
GitHub Discussionsを使用する

### ISSUE THREAD

**Issue by munierujp** [takahiroanno2024/election2024#85]
GitHubには、[GitHub Discussions](https://docs.github.com/ja/discussions)という、その名の通り議論に特化した機能が存在します。
特に以下の点で、議論をする場としてはIssuesよりも適していると思います。

- 賛成票を投じる機能がある
  - Issuesでも 👍/👎 の絵文字をつけられるが、GitHub Discussionsの賛成票は集計される
- 会話がスレッド形式である
  - Issuesで起こりがちな、AさんとBさんが別の話題を続けて投稿した後にCさんがAさんの投稿に言及した結果ごちゃごちゃになるような事態を防げる

よろしければ使用をご検討ください。

## GitHub Discussionsを活用しているリポジトリの例

- https://github.com/increments/qiita-discussions
- https://github.com/vuejs/core

**Comment by TakatsuguImaizumi** [comment]
@munierujp 
当初はDiscussionsの使用も検討していましたが、以下のような理由でIssueに一本化することにしました

- RedditのようなUI/UXは日本人にはなじみが薄い
- DiscussionsでやれることはIssueでも人力のモデレートで実現可能なものが多い
- botの機能が少なく、AIによるモデレーション等、issueでできることがDiscussionsではできないことが多い
- 議論のフォーラムは一つに絞らないと、ユーザーは混乱するし、どこで何をすればいいのかわからなくなるのではないか

Discussionsを使う場合、これをどのように使う想定かまでお伺いできると、前向きに検討できると考えています！

**Comment by munierujp** [comment]
@TakatsuguImaizumi GitHub Discussionsを使われていない理由を挙げていただきありがとうございます。
現時点でGitHub Discussions自体の機能が不足している面もあるようですので、今後の進化に期待しつつ、本件はクローズさせていただきます。
